{
 "title": "Hyperledger Fabric",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Channel",
    "label": "Channel",
    "query": "label_values(gossip_state_height, channel)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current ledger height",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(gossip_state_height{channel = \"$Channel\"})"
    }
   ]
  },
  {
   "title": "chaincode container build duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dockercontroller_chaincode_container_build_duration_sum)by(chaincode)"
    }
   ]
  },
  {
   "title": "Completed deliver requests - Orderer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deliver_requests_completed{channel=\"$Channel\", job=\"fabric-orderer\"}"
    }
   ]
  },
  {
   "title": "Number of endorser proposals received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "endorser_proposals_received" }
   ]
  },
  {
   "title": "Number of successful endorser proposals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "endorser_successful_proposals" }
   ]
  },
  {
   "title": "Gossip total known peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gossip_membership_total_peers_known{channel=\"$Channel\"}"
    }
   ]
  }
 ]
}